# Project

https://nofluffjobs.com/pl/?lang=en&criteria=keyword%3D"{job_name}"'  
browser.get(url.format(job_name=job_name))

job_name = ['data analyst', 'data engineer', 'data scientist']

In [3]:
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.service import Service as FirefoxService

from time import sleep
import re
import csv

In [4]:
service = FirefoxService('./geckodriver.exe') 
browser = Firefox(service=service)  
browser.implicitly_wait(5)

job_names = ['data analyst', 'data engineer', 'data scientist']

In [5]:
def get_organization_data(job_name):
    url = 'https://nofluffjobs.com/pl/?lang=en&criteria=keyword%3D"{job_name}"'  
    browser.get(url.format(job_name=job_name))

    sleep(1)

    try:
        coockies_btn = browser.find_element('id', 'onetrust-accept-btn-handler')
        coockies_btn.click()
        sleep(1)
    except:
        print('coockies ok')

    try:
        notifications_btn = browser.find_element('css selector', '.notification__close')
        notifications_btn.click()
        sleep(1)
    except:
        print('notification ok') 

    
    while True:
        try: 
            browser.find_element('css selector', '.tw-btn-xl').click()
            sleep(1)
        except:
            print('finish') 
            break

    orgs = browser.find_elements('css selector', 'a.posting-list-item')

    results = []

    for org in orgs:
        
        sleep(1)
        name = org.find_element('css selector', 'h3.posting-title__position').get_attribute('innerText')
        company = org.find_element('tag name', 'h4').text
        
        technologies = org.find_element('css selector', 'nfj-posting-item-tiles').text.replace('\n', '')

        location = org.find_element('tag name', 'nfj-posting-item-city').text.split()[0]
        
        salary = org.find_element('css selector', 'nfj-posting-item-salary').text

        if not salary == 'Check Salary Match':
            bounds = re.findall('[0-9]+', salary.replace(' ', ''))
            low_bound = bounds[0]
            high_bound = bounds[1] if len(bounds) > 1 else bounds[0]
            currency = salary.split()[-1]
        else:
            low_bound = ''
            high_bound = ''
            currency = ''

        record = {
            'name': name,
            'company': company,
            'technology': technologies,
            'location': location,
            'salary': {
                'low': low_bound, 
                'high': high_bound, 
                'currency': currency  

            },           
        }
        
        results.append(record) 
 
    return results

In [6]:
final_results = []

In [7]:
for job in job_names:
    final_results.append(get_organization_data(job))

browser.close()

finish
coockies ok
finish
coockies ok
finish

In [8]:
final_results

[[{'name': ' Marketing (Data) Analyst ',
   'company': 'Codete',
   'technology': 'Data  SQL  Python  R',
   'location': 'Remote',
   'salary': {'low': '7000', 'high': '12500', 'currency': 'PLN'}},
  {'name': ' Senior Data Analyst ',
   'company': 'Infogain Technologies Sp. z o.o.',
   'technology': 'Data  SQL  R programming  Data management',
   'location': 'Remote',
   'salary': {'low': '21840', 'high': '26880', 'currency': 'PLN'}},
  {'name': ' Data Analyst ',
   'company': 'Sunscrapers',
   'technology': 'Data  SQL  Data analysis  Data visualization',
   'location': 'Remote',
   'salary': {'low': '20000', 'high': '25000', 'currency': 'PLN'}},
  {'name': ' Data Analyst /Product Analyst ',
   'company': 'apreel Sp. z o.o.',
   'technology': 'Data  SQL  Cloud computing  UX',
   'location': 'Warsaw',
   'salary': {'low': '23520', 'high': '28560', 'currency': 'PLN'}},
  {'name': ' Mid SQL Data Analyst ',
   'company': 'Ośrodek Przetwarzania Informacji - Państwowy Instytut Badawczy',
   'technology': 'Data  SQL  pandas  Python',
   'location': 'Warszawa',
   'salary': {'low': '8000', 'high': '10000', 'currency': 'PLN'}},
  {'name': ' Senior Technical Project Manager ',
   'company': 'RTB House',
   'technology': 'Project Manager  Data analyst  Project management  Web technologies',
   'location': 'Remote',
   'salary': {'low': '27000', 'high': '35000', 'currency': 'PLN'}},
  {'name': ' Data Engineer in Microsoft Azure Cloud ',
   'company': 'Avanade Poland',
   'technology': 'Data  Data analyst  Python  Azure',
   'location': 'Remote',
   'salary': {'low': '19320', 'high': '29400', 'currency': 'PLN'}},
  {'name': ' Data Analyst ',
   'company': 'Schneider Electric',
   'technology': 'Data  Python  SQL  Tableau',
   'location': 'Warsaw',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Analytics Manager - Operation Department ',
   'company': 'T-Mobile Polska',
   'technology': 'Data  Data analyst  Data analysis  Relational database',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' .Net with PowerBI Engineer ',
   'company': 'Capco Poland',
   'technology': 'Data  Data analyst  .NET  Power Query/Power BI',
   'location': 'Remote',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Python Developer - Digital Operation ',
   'company': 'T-Mobile Polska',
   'technology': 'Data  Python  SQL  CI/CD',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Data Engineer - Remote ',
   'company': 'Link Group',
   'technology': 'Data  Azure  Python  SQL',
   'location': 'Remote',
   'salary': {'low': '20000', 'high': '28000', 'currency': 'PLN'}},
  {'name': ' Senior BI Data Engineer ',
   'company': '1dea',
   'technology': 'Data  SQL  BI  DWH',
   'location': 'Remote',
   'salary': {'low': '28560', 'high': '35280', 'currency': 'PLN'}},
  {'name': ' Ms Data Engineer Azure Data Factory ',
   'company': '1dea',
   'technology': 'Data  Python  Azure Data Factory  SQL',
   'location': 'Remote',
   'salary': {'low': '27720', 'high': '31920', 'currency': 'PLN'}},
  {'name': ' Senior Technical Project Manager ',
   'company': 'Crestt',
   'technology': 'Project Manager  Switches  LAN  WAN',
   'location': 'Remote',
   'salary': {'low': '18480', 'high': '23520', 'currency': 'PLN'}},
  {'name': ' Senior PL/SQL Developer ',
   'company': 'AVENGA',
   'technology': 'Data  SQL  Oracle  Jira',
   'location': 'Warszawa',
   'salary': {'low': '18480', 'high': '23520', 'currency': 'PLN'}},
  {'name': ' Data Engineer with Cloud ',
   'company': 'GFT Poland',
   'technology': 'Data  Python  Dataproc for Spark  Dataflow for Apache Beam',
   'location': 'Poznań',
   'salary': {'low': '19320', 'high': '26376', 'currency': 'PLN'}},
  {'name': ' Remote Senior Data Engineer ',
   'company': 'Varwise',
   'technology': 'Data  Scala  Spark  AWS',
   'location': 'Remote',
   'salary': {'low': '7500', 'high': '10000', 'currency': 'USD'}},
  {'name': ' Data Infrastructure Lead ',
   'company': 'IPF Digital',
   'technology': 'Data  AWS  SQL  Python',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Engineer ',
   'company': 'The Codest',
   'technology': 'Data  ETL  AWS  SQL',
   'location': 'Remote',
   'salary': {'low': '17000', 'high': '23000', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer ',
   'company': 'ING BANK ŚLĄSKI SPÓŁKA AKCYJNA',
   'technology': 'Data  Python  PySpark  pandas',
   'location': 'Warszawa',
   'salary': {'low': '14000', 'high': '28000', 'currency': 'PLN'}},
  {'name': ' Ekspert/Ekspertka Data Science ',
   'company': 'UNIQA Polska',
   'technology': 'Data  SQL  AI  OSI',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Data Engineer / Data Architect - Remote ',
   'company': 'Link Group',
   'technology': 'Data  Python  Big data  Hadoop',
   'location': 'Remote',
   'salary': {'low': '28560', 'high': '33600', 'currency': 'PLN'}},
  {'name': ' Staff Data Steward ',
   'company': 'Digital Hub Warsaw at Bayer',
   'technology': 'Data  SQL  NoSQL  Python',
   'location': 'Warsaw',
   'salary': {'low': '18000', 'high': '28000', 'currency': 'PLN'}},
  {'name': ' Senior Technical Project Manager ',
   'company': 'Tangent',
   'technology': 'Project Manager  Project management  Jira  Confluence',
   'location': 'Poznań',
   'salary': {'low': '18000', 'high': '26000', 'currency': 'PLN'}},
  {'name': ' Oracle/SQL Developer ',
   'company': 'T-Mobile Polska',
   'technology': 'Data  SQL  Oracle  MSSQL',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Data Solution Architect/ Data Architect ',
   'company': 'Altimetrik Poland',
   'technology': 'Data  Python  ETL  Azure',
   'location': 'Remote',
   'salary': {'low': '27000', 'high': '37000', 'currency': 'PLN'}},
  {'name': ' Azure Data Engineer - Remote ',
   'company': 'Link Group',
   'technology': 'Data  Azure  CI  Data Lake',
   'location': 'Remote',
   'salary': {'low': '18500', 'high': '24500', 'currency': 'PLN'}},
  {'name': ' Lead Data Engineer ',
   'company': 'Sunscrapers',
   'technology': 'Data  Python  SQL  Data warehouses',
   'location': 'Remote',
   'salary': {'low': '30000', 'high': '45000', 'currency': 'PLN'}},
  {'name': ' Data Engineer ',
   'company': 'Inter Cars S.A.',
   'technology': 'Data  Scala  Data science  Spark',
   'location': 'Remote',
   'salary': {'low': '21000', 'high': '27000', 'currency': 'PLN'}},
  {'name': ' Database Administrator ',
   'company': 'Amelco UK Ltd.',
   'technology': 'Data  SQL  PostgreSQL  K8s',
   'location': 'Warsaw',
   'salary': {'low': '18900', 'high': '25200', 'currency': 'PLN'}},
  {'name': ' Mid Data Modeller - Remote ',
   'company': 'Link Group',
   'technology': 'Data  SQL  English',
   'location': 'Remote',
   'salary': {'low': '20160', 'high': '25200', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer ',
   'company': 'Avenga',
   'technology': 'Data  Kafka  Degree  MySQL',
   'location': 'Remote',
   'salary': {'low': '21840', 'high': '26880', 'currency': 'PLN'}},
  {'name': ' Senior Data Scientist ',
   'company': 'Adform Sp. z o.o.',
   'technology': 'Data  Machine learning  Analytical skills  Python',
   'location': 'Warszawa',
   'salary': {'low': '22400', 'high': '28823', 'currency': 'PLN'}},
  {'name': ' Technical Project Manager ',
   'company': 'Devire',
   'technology': 'Project Manager  Communication skills  Project management  Polish',
   'location': 'Tczew',
   'salary': {'low': '17000', 'high': '20000', 'currency': 'PLN'}},
  {'name': ' Data Engineer ',
   'company': 'ITDS',
   'technology': 'Data  SQL  Data engineering  Python',
   'location': 'Warsaw',
   'salary': {'low': '21000', 'high': '24360', 'currency': 'PLN'}},
  {'name': ' Data Scientist  ',
   'company': 'Avenga',
   'technology': 'Data  Computer vision  NLP  SQL',
   'location': 'Remote',
   'salary': {'low': '25200', 'high': '28560', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer GCP - Remote  ',
   'company': 'Link Group',
   'technology': 'Data  SQL  GCP  BigQuery',
   'location': 'Remote',
   'salary': {'low': '21840', 'high': '30240', 'currency': 'PLN'}},
  {'name': ' Tableau Developer (0.5 FTE) ',
   'company': 'AVENGA',
   'technology': 'Data  Tableau  SQL  Data visualization',
   'location': 'Remote',
   'salary': {'low': '16800', 'high': '20160', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer - Remote  ',
   'company': 'Link Group',
   'technology': 'Data  SQL  dbt  Databricks',
   'location': 'Remote',
   'salary': {'low': '23000', 'high': '25200', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer (Finance Team) ',
   'company': 'Falck Digital Technology Poland Sp. z o.o.',
   'technology': 'Data  SQL  Azure  Python',
   'location': 'Warsaw',
   'salary': {'low': '20000', 'high': '25000', 'currency': 'PLN'}},
  {'name': ' Database Analyst ',
   'company': 'T-Mobile Polska',
   'technology': 'Data  SQL  SAS  Pentaho',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Principal Data Engineer  ',
   'company': 'Digital Hub Warsaw at Bayer',
   'technology': 'Data  Golang  Kafka  REST API',
   'location': 'Warsaw',
   'salary': {'low': '32000', 'high': '42000', 'currency': 'PLN'}},
  {'name': ' Data Engineer (Kafka) ',
   'company': 'Link Group',
   'technology': 'Data  Kafka  SQL  Python',
   'location': 'Remote',
   'salary': {'low': '25200', 'high': '30240', 'currency': 'PLN'}},
  {'name': ' Senior Project Manager ',
   'company': 'VML Enterprise Solutions',
   'technology': 'Project Manager  E-commerce  Project management  Management skills',
   'location': 'Remote',
   'salary': {'low': '20000', 'high': '26000', 'currency': 'PLN'}},
  {'name': ' Senior/Expert Data/ML Engineer ',
   'company': 'Nordea Bank ABP',
   'technology': 'Data  SQL  AI  Degree',
   'location': 'Gdynia',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior APEX Developer ',
   'company': 'AVENGA',
   'technology': 'Data  SQL  Oracle  Apex',
   'location': 'Remote',
   'salary': {'low': '29400', 'high': '33600', 'currency': 'PLN'}},
  {'name': ' Professional Data Engineer ',
   'company': 'AVENGA',
   'technology': 'Data  Snowflake  ETL  Python',
   'location': 'Remote',
   'salary': {'low': '21840', 'high': '24360', 'currency': 'PLN'}},
  {'name': ' Senior Data Scientist (Machine Learning) ',
   'company': 'Welltech',
   'technology': 'Data  SQL  Data analysis  Machine learning',
   'location': 'Remote',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Engineer (Expert) ',
   'company': 'VirtusLab',
   'technology': 'Data  Python  Airflow  Trino',
   'location': 'Remote',
   'salary': {'low': '26000', 'high': '31000', 'currency': 'PLN'}},
  {'name': ' Senior Data Scientist ',
   'company': 'Link Group',
   'technology': 'Data  Python  Hadoop  Machine learning',
   'location': 'Gdynia',
   'salary': {'low': '17000', 'high': '22000', 'currency': 'PLN'}},
  {'name': ' Data Engineer ',
   'company': 'ROCKWOOL GBS',
   'technology': 'Data  SQL  NoSQL  Data pipelines',
   'location': 'Poznań',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Data Modeller ',
   'company': 'AVENGA',
   'technology': 'Data  SQL  Data modelling  Data structures',
   'location': 'Gdańsk',
   'salary': {'low': '25200', 'high': '28560', 'currency': 'PLN'}},
  {'name': ' Senior Big Data Developer (Java/Scala) ',
   'company': 'Jit Team',
   'technology': 'Data  Java  Scala  Spark',
   'location': 'Warsaw',
   'salary': {'low': '19000', 'high': '27300', 'currency': 'PLN'}},
  {'name': ' Delivery Manager for IoT/BSS/OSS project in Europe ',
   'company': 'Intellias',
   'technology': 'Project Manager  IoT  BSS  OSS',
   'location': 'Remote',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Lead Data Architect ',
   'company': 'Digital Hub Warsaw at Bayer',
   'technology': 'Data  SQL  Degree  Market analytics',
   'location': 'Warsaw',
   'salary': {'low': '24000', 'high': '34000', 'currency': 'PLN'}},
  {'name': ' Senior Snowflake Developer ',
   'company': 'AVENGA',
   'technology': 'Data  SQL  Data modeling  ETL',
   'location': 'Remote',
   'salary': {'low': '23520', 'high': '26880', 'currency': 'PLN'}},
  {'name': ' Data Engineer (Future Opening) ',
   'company': 'Xebia sp. z o.o.',
   'technology': 'Data  Python  Airflow  PySpark',
   'location': 'Remote',
   'salary': {'low': '16700', 'high': '31200', 'currency': 'PLN'}},
  {'name': ' Senior Dev in Machine Learning - z j. niemieckim ',
   'company': 'dmTECH',
   'technology': 'Data  GCP  CI  Clean Code',
   'location': 'Remote',
   'salary': {'low': '15120', 'high': '28896', 'currency': 'PLN'}},
  {'name': ' Programista Oracle ',
   'company': 'Crestt sp. z o.o.',
   'technology': 'Data  Oracle  SQL  Java',
   'location': 'Łódź',
   'salary': {'low': '21840', 'high': '25200', 'currency': 'PLN'}},
  {'name': ' Senior Talend ETL Specialist ',
   'company': 'JSS Associates',
   'technology': 'Data  ETL  AWS Cloud  Data management',
   'location': 'Warsaw',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Engineer ',
   'company': 'Raiffeisen Tech',
   'technology': 'Data  Python  Big data  AWS',
   'location': 'Warszawa',
   'salary': {'low': '20000', 'high': '26000', 'currency': 'PLN'}},
  {'name': ' ClickHouse Solutions Support Engineer / DBA ',
   'company': 'Alttinity',
   'technology': 'Data  SQL  C++  Linux',
   'location': 'Remote',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Inżynier/ka ds. procesowania i dystrybucji danych ',
   'company': 'ING BANK ŚLĄSKI SPÓŁKA AKCYJNA',
   'technology': 'Data  Red Hat  .NET  GCP',
   'location': 'Warszawa',
   'salary': {'low': '12000', 'high': '14000', 'currency': 'PLN'}},
  {'name': ' Senior Project Manager with German ',
   'company': 'Link Group',
   'technology': 'Project Manager  Communication skills  Project management  Product development',
   'location': 'Remote',
   'salary': {'low': '23520', 'high': '25200', 'currency': 'PLN'}},
  {'name': ' PostGreSQL Database Administrator ',
   'company': 'Euroclear',
   'technology': 'Data  SQL  PostgreSQL  Performance tuning',
   'location': 'Kraków',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Experienced Data Engineer ',
   'company': 'Euroclear',
   'technology': 'Data  Spark  SQL  Scala',
   'location': 'Kraków',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Database Administrator (Azure) ',
   'company': 'SoftServe',
   'technology': 'Data  Oracle  Azure  MySQL',
   'location': 'Remote',
   'salary': {'low': '16000', 'high': '20000', 'currency': 'PLN'}},
  {'name': ' Senior Data Engineer z j. niemieckim  ',
   'company': 'dmTECH',
   'technology': 'Data  Big data  Spark  Hive',
   'location': 'Remote',
   'salary': {'low': '15120', 'high': '28896', 'currency': 'PLN'}},
  {'name': ' Data Engineer ',
   'company': 'CommerzBank',
   'technology': 'Data  SQL  DWH  Unix',
   'location': 'Łódź',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Solutions Architect  ',
   'company': 'Link Group',
   'technology': 'Data  Data analytics  Data analysis  Power Curve',
   'location': 'Remote',
   'salary': {'low': '25200', 'high': '30240', 'currency': 'PLN'}},
  {'name': ' Programista Oracle  ',
   'company': 'HRose Agency',
   'technology': 'Data  SQL  Oracle  Java',
   'location': 'Łódź',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Data Engineer  ',
   'company': 'N-iX',
   'technology': 'Data  ETL  Data Warehousing  GCP',
   'location': 'Remote',
   'salary': {'low': '4500', 'high': '6100', 'currency': 'USD'}},
  {'name': ' Remote Data Engineer  ',
   'company': 'Kingfisher plc.',
   'technology': 'Data  Python  AWS  Data modelling',
   'location': 'Remote',
   'salary': {'low': '15000', 'high': '19000', 'currency': 'PLN'}},
  {'name': ' Program and Transition Manager ',
   'company': 'Altimetrik Poland',
   'technology': 'Project Manager  Jira  SAFe  Altas',
   'location': 'Remote',
   'salary': {'low': '25000', 'high': '29500', 'currency': 'PLN'}},
  {'name': ' Specjalista ds. Danych i Raportów Ryzyka  ',
   'company': 'Nest Bank',
   'technology': 'Data  SQL  Python  Azure Databricks',
   'location': 'Warszawa',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Data Architect - Remote ',
   'company': 'ITDS',
   'technology': 'Data  Data management  Data architecture  Data Governance',
   'location': 'Remote',
   'salary': {'low': '23100', 'high': '27300', 'currency': 'PLN'}},
  {'name': ' Senior Big Data Engineer (AWS) ',
   'company': 'SoftServe',
   'technology': 'Data  Python  AWS  Airflow',
   'location': 'Remote',
   'salary': {'low': '20000', 'high': '28000', 'currency': 'PLN'}},
  {'name': ' Senior Machine Learning Engineer (Future Opening) ',
   'company': 'Xebia sp. z o.o.',
   'technology': 'Data  Python  Cloud  CI/CD',
   'location': 'Remote',
   'salary': {'low': '20100', 'high': '33600', 'currency': 'PLN'}},
  {'name': ' Data Scientist ',
   'company': 'Connectis_',
   'technology': 'Data  AI  Machine learning  Python',
   'location': 'Remote',
   'salary': {'low': '25200', 'high': '28560', 'currency': 'PLN'}},
  {'name': ' Big Data DBA  ',
   'company': 'Adaptiq',
   'technology': 'Data  K8  OCP  WebLogic',
   'location': 'Remote',
   'salary': {'low': '6500', 'high': '6800', 'currency': 'USD'}},
  {'name': ' Senior Data Modeller ',
   'company': 'Devire',
   'technology': 'Data  SQL  Data modelling  Data structures',
   'location': 'Gdańsk',
   'salary': {'low': '25200', 'high': '29400', 'currency': 'PLN'}},
  {'name': ' Data Engineer - Fulfillment (part time) ',
   'company': 'Tesco Technology',
   'technology': 'Data  Scala  Hadoop  Kafka',
   'location': 'Kraków',
   'salary': {'low': '15000', 'high': '23000', 'currency': 'PLN'}},
  {'name': ' Python Developer ',
   'company': 'ROCKWOOL GBS',
   'technology': 'Data  Python  Machine learning  TensorFlow',
   'location': 'Poznań',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Senior Process & Project Expert OEE KPI - Remote ',
   'company': 'Link Group',
   'technology': 'Project Manager  OEE  PostgreSQL  Project management',
   'location': 'Remote',
   'salary': {'low': '24000', 'high': '27500', 'currency': 'PLN'}},
  {'name': ' Senior Data Scientist ',
   'company': 'Devire',
   'technology': 'Data  Python  SQL  DAX',
   'location': 'Łódź',
   'salary': {'low': '25200', 'high': '29400', 'currency': 'PLN'}},
  {'name': ' Data Engineer (Senior/Principal) ',
   'company': 'Addepto',
   'technology': 'Data  Python  Big data  Databricks',
   'location': 'Remote',
   'salary': {'low': '21000', 'high': '31920', 'currency': 'PLN'}},
  {'name': ' Data Warehouse Engineer ',
   'company': 'HSBC Technology Poland',
   'technology': 'Data  Trino  Dremio  Data Lake',
   'location': 'Kraków',
   'salary': {'low': '23000', 'high': '30000', 'currency': 'PLN'}},
  {'name': ' Data Engineer | Branża elektroniczna ',
   'company': 'Edge One Solutions Sp. z o.o.',
   'technology': 'Data  Hive  Spark  ETL',
   'location': 'Remote',
   'salary': {'low': '', 'high': '', 'currency': ''}},
  {'name': ' Middle Integration Engineer ',
   'company': 'N-iX',
   'technology': 'Data  Ruby  Python  SQL',
   'location': 'Remote',
   'salary': {'low': '3000', 'high': '3700', 'currency': 'USD'}},
  {'name': ' Database Reliability Engineer ',
   'company': 'monday.com',
   'technology': 'Data  SQL  RDBMS  MySQL',
   'location': 'Warsaw',
   'salary': {'low': '57000', 'high': '64000', 'currency': 'PLN'}},
  {'name': ' Lead Data Software Engineer (Java, GCP) ',
   'company': 'EPAM Systems',
   'technology': 'Data  Java  SQL  ETL',
   'location': 'Wrocław',

In [9]:
# Cesta k výstupnímu souboru CSV
csv_file_path = "job_offer.csv"

# Zápis do CSV souboru
with open(csv_file_path, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    
    # Zápis záhlaví
    writer.writerow(['Name', 'Company', 'Location', 'Technologies', 'Salary Low', 'Salary High', 'Currency'])
    
    # Zápis jednotlivých pracovních nabídek
    for job in final_results:

        for listing  in job:
            name = listing['name']
            company = listing['company']
            location = listing['location']
            technologies = listing['technology']
            salary_low = listing['salary']['low']
            salary_high = listing['salary']['high']
            salary_currency = listing['salary']['currency']

        # Zapíšeme řádek do CSV
            writer.writerow([name, company, location, technologies, salary_low, salary_high, salary_currency])

print(f"CSV soubor byl úspěšně uložen jako {csv_file_path}")

CSV soubor byl úspěšně uložen jako job_offer.csv